version: "3.9"
services:
  icarus-service-prod:
    container_name: icarus-service-prod
    extends:
      file: docker-compose.yml
      service: microservice
    volumes:
      - ./app:/app
    entrypoint: ./start-prod.sh
    env_file:
      - .env
    networks:
      - icarus_services

networks:
  icarus_services:
    external: true
