version: "3.9"
services:
  icarus-companies-service:
    container_name: icarus-companies-service
    image: node:14.17-alpine
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env

