version: "3.9"
services:
  api-icarus:
    container_name: api-icarus
    image: node:14.17-alpine
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env

  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    env_file:
      - .env
