version: "3.9"
services:
  api-icarus-dev:
    container_name: api-icarus-dev
    extends:
      file: docker-compose.yml
      service: api-icarus
    volumes:
      - ./app:/app
    entrypoint: ./start-develop.sh
    depends_on:
      - icarus-database
    networks:
      - services

  icarus-database:
    container_name: icarus-database
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
    networks:
      - services

  nats:
    container_name: icarus-nats-dev
    extends:
      file: docker-compose.yml
      service: nats
    networks:
      services:
        aliases:
          - '${API_NATS_SERVER_HOST}'

networks:
  services:
    driver: bridge


