version: "3.9"
services:
  api-lululove-prod:
    container_name: api-lululove-prod
    extends:
      file: docker-compose.yml
      service: api-lululove
    restart: always
    entrypoint: ./start-prod.sh
    depends_on:
      - nats

  nats:
    container_name: lululove-nats-prod
    extends:
      file: docker-compose.yml
      service: nats
    networks:
      services:
        aliases:
          - '${API_NATS_SERVER_HOST}'

networks:
  services:
    driver: bridge
