version: "3.9"
services:
  api-lululove-prod:
    container_name:  ${APP_CONTAINER_NAME}
    extends:
      file: docker-compose.yml
      service: api-icarurs
    restart: always
    entrypoint: ./start-prod.sh
    depends_on:
      - nats

  nats:
    container_name: icarus-nats-prod
    extends:
      file: docker-compose.yml
      service: nats
    networks:
      services:
        aliases:
          - '${API_NATS_SERVER_HOST}'

networks:
  services:
    driver: bridge
